#ifndef ESMTRANSLATIONLIB_ESMDEFINES_H
#define ESMTRANSLATIONLIB_ESMDEFINES_H

#if defined(ESMTRANSLATIONLIB_EXPORT)
# define ESMTRANSLATIONLIB_API extern "C" __declspec(dllexport)
# define ESMTRANSLATIONLIB_API_CLASS __declspec(dllexport)
#else
# define ESMTRANSLATIONLIB_API
# define ESMTRANSLATIONLIB_API_CLASS
#endif

#endif //ESMTRANSLATIONLIB_ESMDEFINES_H
